// AUTO-GENERATED BY build_webui.js - DO NOT EDIT MANUALLY
#pragma once

namespace ABDMS2000 {
    inline constexpr const char* kVersionString = "1.0.0";
    inline constexpr const char* kBuildNumber = "2026.09.15.1757";
    inline constexpr const char* kBuildTimestamp = "2026-09-15T15:57:49.776Z";
    inline constexpr const char* kProductName = "ABDMS2000";
    inline constexpr const char* kManufacturer = "ajabadia";
}
