// AUTO-GENERATED BY build_webui.js - DO NOT EDIT MANUALLY
#pragma once

namespace ABDMS2000 {
    inline constexpr const char* kVersionString = "1.0.0";
    inline constexpr const char* kBuildNumber = "2026.08.24.1511";
    inline constexpr const char* kBuildTimestamp = "2026-08-24T13:11:45.677Z";
    inline constexpr const char* kProductName = "ABDMS2000";
    inline constexpr const char* kManufacturer = "ajabadia";
}
