// AUTO-GENERATED BY Scripts/generate_host_model_id.js - DO NOT EDIT MANUALLY
//
// Identidad del sintetizador anfitrion, derivada del contrato canonico
// (ABDBankManager/Source/Contracts/Models/korg-ms2000.ts -> korgAbdSm002Contract)
// a traves del artefacto sincronizado
// WebUI/abdbank/src/contracts/gen/modelContracts.gen.js.
//
// Regenerar tras cualquier cambio de contrato:
//   node Scripts/generate_host_model_id.js
// (lo hacen el paso 1 de build.bat y `npm run generate`)

#pragma once

namespace ABDMS2000 {

/** modelId canonico del host: lo que anuncia la accion bridge `hostModel`. */
inline constexpr const char* kHostModelId = "abd-sm002";

/** Nombre y fabricante del contrato (diagnostico / logs). */
inline constexpr const char* kHostModelDisplayName = "ABD MS2000 (SM002)";
inline constexpr const char* kHostModelManufacturer = "ABDSynths";

/**
 * Nivel de puente del host (capacidades, no fechas). El Bank Manager embebido
 * lo usa para decir si el binario de al lado sabe anunciar su modelo (>=2),
 * responder su ficha (>=3) y mover bytes por el puente MIDI de hardware (>=4).
 */
inline constexpr int kHostBridgeProtocol = 4;

/** Revision del codigo en el momento de generar este header. */
inline constexpr const char* kHostBuildRevision = "5b7d69ce9";

/**
 * Sello de build del binario: la unidad que incluya este header se compila con
 * su propia fecha/hora, que es lo que identifica al ejecutable que hay al otro
 * lado del bridge.
 */
#define ABD_HOST_BUILD_STAMP (__DATE__ " " __TIME__)

} // namespace ABDMS2000
