// AUTO-GENERATED BY registry_generator.js - DO NOT EDIT MANUALLY
#pragma once
#if __has_include(<juce_audio_processors/juce_audio_processors.h>)
#include <juce_audio_processors/juce_audio_processors.h>
#define ABD_HAS_JUCE 1
#else
#define ABD_HAS_JUCE 0
#endif
#include <string>
#include <vector>
#include <unordered_map>

namespace ABDMS2000 {

enum class ParamType {
    Continuous,
    Integer,
    Choice,
    Boolean
};

struct ParameterMeta {
    const char* id;
    const char* name;
    const char* group;
    int cc; // -1 if none
    float min;
    float max;
    float defaultValue;
    float skew;
    ParamType type;
    const char* unit;
    int sysexOffset; // -1 if none (auto-computed by generator)
    std::vector<const char*> choices;
};

class ParameterRegistry {
public:
    static const std::vector<ParameterMeta>& getAllParameters();
    static const ParameterMeta* getParameter(const std::string& id);
#if ABD_HAS_JUCE
    static juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();
#endif
};

namespace ParamIDs {
    inline constexpr const char* masterVolume = "masterVolume";
    inline constexpr const char* synthMode = "synthMode";
    inline constexpr const char* voiceMode = "voiceMode";
    inline constexpr const char* unisonDetune = "unisonDetune";
    inline constexpr const char* unisonSpread = "unisonSpread";
    inline constexpr const char* portamentoTime = "portamentoTime";
    inline constexpr const char* portamentoOn = "portamentoOn";
    inline constexpr const char* osc1Wave = "osc1Wave";
    inline constexpr const char* osc1DwgsWave = "osc1DwgsWave";
    inline constexpr const char* osc1Ctrl1 = "osc1Ctrl1";
    inline constexpr const char* osc1Ctrl2 = "osc1Ctrl2";
    inline constexpr const char* osc2Wave = "osc2Wave";
    inline constexpr const char* osc2ModType = "osc2ModType";
    inline constexpr const char* osc2Semitone = "osc2Semitone";
    inline constexpr const char* osc2Tune = "osc2Tune";
    inline constexpr const char* mixOsc1Level = "mixOsc1Level";
    inline constexpr const char* mixOsc2Level = "mixOsc2Level";
    inline constexpr const char* mixNoiseLevel = "mixNoiseLevel";
    inline constexpr const char* filterType = "filterType";
    inline constexpr const char* filterCutoff = "filterCutoff";
    inline constexpr const char* filterResonance = "filterResonance";
    inline constexpr const char* filterEg1Int = "filterEg1Int";
    inline constexpr const char* filterKeyTrack = "filterKeyTrack";
    inline constexpr const char* ampLevel = "ampLevel";
    inline constexpr const char* ampPan = "ampPan";
    inline constexpr const char* ampDistortion = "ampDistortion";
    inline constexpr const char* ampKeyTrack = "ampKeyTrack";
    inline constexpr const char* eg1Attack = "eg1Attack";
    inline constexpr const char* eg1Decay = "eg1Decay";
    inline constexpr const char* eg1Sustain = "eg1Sustain";
    inline constexpr const char* eg1Release = "eg1Release";
    inline constexpr const char* eg2Attack = "eg2Attack";
    inline constexpr const char* eg2Decay = "eg2Decay";
    inline constexpr const char* eg2Sustain = "eg2Sustain";
    inline constexpr const char* eg2Release = "eg2Release";
    inline constexpr const char* lfo1Wave = "lfo1Wave";
    inline constexpr const char* lfo1Freq = "lfo1Freq";
    inline constexpr const char* lfo1KeySync = "lfo1KeySync";
    inline constexpr const char* lfo1TempoSync = "lfo1TempoSync";
    inline constexpr const char* lfo1SyncNote = "lfo1SyncNote";
    inline constexpr const char* lfo2Wave = "lfo2Wave";
    inline constexpr const char* lfo2Freq = "lfo2Freq";
    inline constexpr const char* lfo2KeySync = "lfo2KeySync";
    inline constexpr const char* lfo2TempoSync = "lfo2TempoSync";
    inline constexpr const char* lfo2SyncNote = "lfo2SyncNote";
    inline constexpr const char* eqLowFreq = "eqLowFreq";
    inline constexpr const char* eqLowGain = "eqLowGain";
    inline constexpr const char* eqHighFreq = "eqHighFreq";
    inline constexpr const char* eqHighGain = "eqHighGain";
    inline constexpr const char* modFxOn = "modFxOn";
    inline constexpr const char* modFxType = "modFxType";
    inline constexpr const char* modFxSpeed = "modFxSpeed";
    inline constexpr const char* modFxDepth = "modFxDepth";
    inline constexpr const char* modFxFeedback = "modFxFeedback";
    inline constexpr const char* delayOn = "delayOn";
    inline constexpr const char* delayType = "delayType";
    inline constexpr const char* delayTime = "delayTime";
    inline constexpr const char* delayDepth = "delayDepth";
    inline constexpr const char* delayFeedback = "delayFeedback";
    inline constexpr const char* arpOn = "arpOn";
    inline constexpr const char* arpType = "arpType";
    inline constexpr const char* arpRange = "arpRange";
    inline constexpr const char* arpGate = "arpGate";
    inline constexpr const char* arpLatch = "arpLatch";
    inline constexpr const char* arpResolution = "arpResolution";
    inline constexpr const char* modSeqResolution = "modSeqResolution";
    inline constexpr const char* assignablePedal = "assignablePedal";
    inline constexpr const char* assignableSwitch = "assignableSwitch";
    inline constexpr const char* patch1Source = "patch1Source";
    inline constexpr const char* patch1Destination = "patch1Destination";
    inline constexpr const char* patch1Intensity = "patch1Intensity";
    inline constexpr const char* patch2Source = "patch2Source";
    inline constexpr const char* patch2Destination = "patch2Destination";
    inline constexpr const char* patch2Intensity = "patch2Intensity";
    inline constexpr const char* patch3Source = "patch3Source";
    inline constexpr const char* patch3Destination = "patch3Destination";
    inline constexpr const char* patch3Intensity = "patch3Intensity";
    inline constexpr const char* patch4Source = "patch4Source";
    inline constexpr const char* patch4Destination = "patch4Destination";
    inline constexpr const char* patch4Intensity = "patch4Intensity";
    inline constexpr const char* modSeqOn = "modSeqOn";
    inline constexpr const char* modSeqType = "modSeqType";
    inline constexpr const char* modSeqSmooth = "modSeqSmooth";
    inline constexpr const char* synthVocoderMode = "synthVocoderMode";
    inline constexpr const char* vocoderCarrierSrc = "vocoderCarrierSrc";
    inline constexpr const char* vocoderFormantShift = "vocoderFormantShift";
    inline constexpr const char* vocoderHpfLevel = "vocoderHpfLevel";
    inline constexpr const char* vocoderGateSense = "vocoderGateSense";
    inline constexpr const char* vocoderDirectLevel = "vocoderDirectLevel";
    inline constexpr const char* vocoderBandLevel1 = "vocoderBandLevel1";
    inline constexpr const char* vocoderBandLevel2 = "vocoderBandLevel2";
    inline constexpr const char* vocoderBandLevel3 = "vocoderBandLevel3";
    inline constexpr const char* vocoderBandLevel4 = "vocoderBandLevel4";
    inline constexpr const char* vocoderBandLevel5 = "vocoderBandLevel5";
    inline constexpr const char* vocoderBandLevel6 = "vocoderBandLevel6";
    inline constexpr const char* vocoderBandLevel7 = "vocoderBandLevel7";
    inline constexpr const char* vocoderBandLevel8 = "vocoderBandLevel8";
    inline constexpr const char* vocoderBandLevel9 = "vocoderBandLevel9";
    inline constexpr const char* vocoderBandLevel10 = "vocoderBandLevel10";
    inline constexpr const char* vocoderBandLevel11 = "vocoderBandLevel11";
    inline constexpr const char* vocoderBandLevel12 = "vocoderBandLevel12";
    inline constexpr const char* vocoderBandLevel13 = "vocoderBandLevel13";
    inline constexpr const char* vocoderBandLevel14 = "vocoderBandLevel14";
    inline constexpr const char* vocoderBandLevel15 = "vocoderBandLevel15";
    inline constexpr const char* vocoderBandLevel16 = "vocoderBandLevel16";
} // namespace ParamIDs
} // namespace ABDMS2000
