// AUTO-GENERATED BY registry_generator.js - DO NOT EDIT MANUALLY
#pragma once
#include <juce_audio_processors/juce_audio_processors.h>
#include <string>
#include <vector>
#include <unordered_map>

namespace ABDMS2000 {

enum class ParamType {
    Continuous,
    Integer,
    Choice,
    Boolean
};

struct ParameterMeta {
    const char* id;
    const char* name;
    const char* group;
    int cc; // -1 if none
    float min;
    float max;
    float defaultValue;
    float skew;
    ParamType type;
    const char* unit;
    int sysexOffset; // -1 if none
    std::vector<const char*> choices;
};

class ParameterRegistry {
public:
    static const std::vector<ParameterMeta>& getAllParameters();
    static const ParameterMeta* getParameter(const std::string& id);
    static juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();
};

namespace ParamIDs {
    inline constexpr const char* masterVolume = "masterVolume";
    inline constexpr const char* synthMode = "synthMode";
    inline constexpr const char* voiceMode = "voiceMode";
    inline constexpr const char* unisonDetune = "unisonDetune";
    inline constexpr const char* unisonSpread = "unisonSpread";
    inline constexpr const char* portamentoTime = "portamentoTime";
    inline constexpr const char* osc1Wave = "osc1Wave";
    inline constexpr const char* osc1DwgsWave = "osc1DwgsWave";
    inline constexpr const char* osc1Ctrl1 = "osc1Ctrl1";
    inline constexpr const char* osc1Ctrl2 = "osc1Ctrl2";
    inline constexpr const char* osc2Wave = "osc2Wave";
    inline constexpr const char* osc2ModType = "osc2ModType";
    inline constexpr const char* osc2Semitone = "osc2Semitone";
    inline constexpr const char* osc2Tune = "osc2Tune";
    inline constexpr const char* mixOsc1Level = "mixOsc1Level";
    inline constexpr const char* mixOsc2Level = "mixOsc2Level";
    inline constexpr const char* mixNoiseLevel = "mixNoiseLevel";
    inline constexpr const char* filterType = "filterType";
    inline constexpr const char* filterCutoff = "filterCutoff";
    inline constexpr const char* filterResonance = "filterResonance";
    inline constexpr const char* filterEg1Int = "filterEg1Int";
    inline constexpr const char* filterKeyTrack = "filterKeyTrack";
    inline constexpr const char* ampLevel = "ampLevel";
    inline constexpr const char* ampPan = "ampPan";
    inline constexpr const char* ampDistortion = "ampDistortion";
    inline constexpr const char* ampKeyTrack = "ampKeyTrack";
    inline constexpr const char* eg1Attack = "eg1Attack";
    inline constexpr const char* eg1Decay = "eg1Decay";
    inline constexpr const char* eg1Sustain = "eg1Sustain";
    inline constexpr const char* eg1Release = "eg1Release";
    inline constexpr const char* eg2Attack = "eg2Attack";
    inline constexpr const char* eg2Decay = "eg2Decay";
    inline constexpr const char* eg2Sustain = "eg2Sustain";
    inline constexpr const char* eg2Release = "eg2Release";
    inline constexpr const char* lfo1Wave = "lfo1Wave";
    inline constexpr const char* lfo1Freq = "lfo1Freq";
    inline constexpr const char* lfo1KeySync = "lfo1KeySync";
    inline constexpr const char* lfo2Wave = "lfo2Wave";
    inline constexpr const char* lfo2Freq = "lfo2Freq";
    inline constexpr const char* lfo2KeySync = "lfo2KeySync";
} // namespace ParamIDs
} // namespace ABDMS2000
