// AUTO-GENERATED BY registry_generator.js - DO NOT EDIT MANUALLY
#include "ParameterRegistry.gen.h"

namespace ABDMS2000 {

static const std::vector<ParameterMeta> kAllParameters = {
    { "masterVolume", "Master Volume", "Master", 7, 0.0f, 1.0f, 0.8f, 1.0f, ParamType::Continuous, "dB", -1, {} },
    { "synthMode", "Synth Profile Mode", "Global", -1, 0.0f, 2.0f, 0.0f, 1.0f, ParamType::Choice, "", -1, { "MS2000", "microKORG", "Advanced" } },
    { "voiceMode", "Voice Assign", "Voice", -1, 0.0f, 2.0f, 1.0f, 1.0f, ParamType::Choice, "", 0, { "Mono", "Poly", "Unison" } },
    { "unisonDetune", "Unison Detune", "Voice", -1, 0.0f, 99.0f, 10.0f, 1.0f, ParamType::Integer, "cents", 1, {} },
    { "unisonSpread", "Unison Spread", "Voice", -1, 0.0f, 1.0f, 0.5f, 1.0f, ParamType::Continuous, "", -1, {} },
    { "portamentoTime", "Portamento Time", "Pitch", 5, 0.0f, 127.0f, 0.0f, 0.35f, ParamType::Integer, "", 2, {} },
    { "osc1Wave", "OSC1 Waveform", "OSC1", 77, 0.0f, 7.0f, 0.0f, 1.0f, ParamType::Choice, "", 3, { "Saw", "Square", "Triangle", "Sine", "VoxWave", "DWGS", "Noise", "AudioIn" } },
    { "osc1DwgsWave", "OSC1 DWGS Wave", "OSC1", -1, 1.0f, 64.0f, 1.0f, 1.0f, ParamType::Integer, "", 4, {} },
    { "osc1Ctrl1", "OSC1 Control 1", "OSC1", 14, 0.0f, 127.0f, 0.0f, 1.0f, ParamType::Integer, "", 5, {} },
    { "osc1Ctrl2", "OSC1 Control 2", "OSC1", 15, 0.0f, 127.0f, 0.0f, 1.0f, ParamType::Integer, "", 6, {} },
    { "osc2Wave", "OSC2 Waveform", "OSC2", 78, 0.0f, 2.0f, 0.0f, 1.0f, ParamType::Choice, "", 7, { "Saw", "Square", "Triangle" } },
    { "osc2ModType", "OSC2 Modulation Type", "OSC2", -1, 0.0f, 3.0f, 0.0f, 1.0f, ParamType::Choice, "", 8, { "Off", "Ring", "Sync", "RingSync" } },
    { "osc2Semitone", "OSC2 Semitone", "OSC2", 16, -24.0f, 24.0f, 0.0f, 1.0f, ParamType::Integer, "st", 9, {} },
    { "osc2Tune", "OSC2 Fine Tune", "OSC2", 17, -50.0f, 50.0f, 0.0f, 1.0f, ParamType::Integer, "cents", 10, {} },
    { "mixOsc1Level", "Mixer OSC1 Level", "Mixer", 20, 0.0f, 127.0f, 127.0f, 1.0f, ParamType::Integer, "", 11, {} },
    { "mixOsc2Level", "Mixer OSC2 Level", "Mixer", 21, 0.0f, 127.0f, 0.0f, 1.0f, ParamType::Integer, "", 12, {} },
    { "mixNoiseLevel", "Mixer Noise Level", "Mixer", 22, 0.0f, 127.0f, 0.0f, 1.0f, ParamType::Integer, "", 13, {} },
    { "filterType", "Filter Type", "Filter", 83, 0.0f, 3.0f, 0.0f, 1.0f, ParamType::Choice, "", 14, { "LPF24", "LPF12", "BPF12", "HPF12" } },
    { "filterCutoff", "Filter Cutoff", "Filter", 74, 0.0f, 127.0f, 127.0f, 0.45f, ParamType::Integer, "Hz", 15, {} },
    { "filterResonance", "Filter Resonance", "Filter", 71, 0.0f, 127.0f, 0.0f, 1.0f, ParamType::Integer, "", 16, {} },
    { "filterEg1Int", "Filter EG1 Intensity", "Filter", 79, -63.0f, 63.0f, 0.0f, 1.0f, ParamType::Integer, "", 17, {} },
    { "filterKeyTrack", "Filter Keyboard Track", "Filter", 80, -63.0f, 63.0f, 0.0f, 1.0f, ParamType::Integer, "", 18, {} },
    { "ampLevel", "Amp Level", "Amp", -1, 0.0f, 127.0f, 100.0f, 1.0f, ParamType::Integer, "", 19, {} },
    { "ampPan", "Amp Pan", "Amp", 10, -64.0f, 63.0f, 0.0f, 1.0f, ParamType::Integer, "", 20, {} },
    { "ampDistortion", "Amp Distortion", "Amp", 81, 0.0f, 1.0f, 0.0f, 1.0f, ParamType::Boolean, "", 21, {} },
    { "ampKeyTrack", "Amp Keyboard Track", "Amp", 82, -63.0f, 63.0f, 0.0f, 1.0f, ParamType::Integer, "", 22, {} },
    { "eg1Attack", "EG1 Attack", "EG1", 23, 0.0f, 127.0f, 0.0f, 0.35f, ParamType::Integer, "ms", 23, {} },
    { "eg1Decay", "EG1 Decay", "EG1", 24, 0.0f, 127.0f, 64.0f, 0.35f, ParamType::Integer, "ms", 24, {} },
    { "eg1Sustain", "EG1 Sustain", "EG1", 25, 0.0f, 127.0f, 0.0f, 1.0f, ParamType::Integer, "", 25, {} },
    { "eg1Release", "EG1 Release", "EG1", 26, 0.0f, 127.0f, 40.0f, 0.35f, ParamType::Integer, "ms", 26, {} },
    { "eg2Attack", "EG2 Attack", "EG2", 73, 0.0f, 127.0f, 0.0f, 0.35f, ParamType::Integer, "ms", 27, {} },
    { "eg2Decay", "EG2 Decay", "EG2", 75, 0.0f, 127.0f, 64.0f, 0.35f, ParamType::Integer, "ms", 28, {} },
    { "eg2Sustain", "EG2 Sustain", "EG2", 27, 0.0f, 127.0f, 127.0f, 1.0f, ParamType::Integer, "", 29, {} },
    { "eg2Release", "EG2 Release", "EG2", 72, 0.0f, 127.0f, 20.0f, 0.35f, ParamType::Integer, "ms", 30, {} },
    { "lfo1Wave", "LFO1 Waveform", "LFO1", 86, 0.0f, 3.0f, 0.0f, 1.0f, ParamType::Choice, "", 31, { "Saw", "Square", "Triangle", "SampleHold" } },
    { "lfo1Freq", "LFO1 Frequency", "LFO1", 76, 0.0f, 127.0f, 30.0f, 0.4f, ParamType::Integer, "Hz", 32, {} },
    { "lfo1KeySync", "LFO1 Key Sync", "LFO1", 85, 0.0f, 2.0f, 0.0f, 1.0f, ParamType::Choice, "", 33, { "Off", "Timbre", "Voice" } },
    { "lfo2Wave", "LFO2 Waveform", "LFO2", 88, 0.0f, 3.0f, 2.0f, 1.0f, ParamType::Choice, "", 34, { "Saw", "Square", "Sine", "SampleHold" } },
    { "lfo2Freq", "LFO2 Frequency", "LFO2", 87, 0.0f, 127.0f, 50.0f, 0.4f, ParamType::Integer, "Hz", 35, {} },
    { "lfo2KeySync", "LFO2 Key Sync", "LFO2", 90, 0.0f, 2.0f, 0.0f, 1.0f, ParamType::Choice, "", 36, { "Off", "Timbre", "Voice" } }
};

const std::vector<ParameterMeta>& ParameterRegistry::getAllParameters() {
    return kAllParameters;
}

const ParameterMeta* ParameterRegistry::getParameter(const std::string& id) {
    static const std::unordered_map<std::string, const ParameterMeta*> kLookup = []() {
        std::unordered_map<std::string, const ParameterMeta*> map;
        for (const auto& meta : kAllParameters) {
            map[meta.id] = &meta;
        }
        return map;
    }();

    auto it = kLookup.find(id);
    return (it != kLookup.end()) ? it->second : nullptr;
}

juce::AudioProcessorValueTreeState::ParameterLayout ParameterRegistry::createParameterLayout() {
    std::vector<std::unique_ptr<juce::RangedAudioParameter>> layoutParams;

    for (const auto& meta : kAllParameters) {
        if (meta.type == ParamType::Choice && !meta.choices.empty()) {
            juce::StringArray choiceArray;
            for (const auto* c : meta.choices) {
                choiceArray.add(c);
            }
            layoutParams.push_back(std::make_unique<juce::AudioParameterChoice>(
                juce::ParameterID(meta.id, 1),
                meta.name,
                choiceArray,
                static_cast<int>(meta.defaultValue)
            ));
        } else if (meta.type == ParamType::Boolean) {
            layoutParams.push_back(std::make_unique<juce::AudioParameterBool>(
                juce::ParameterID(meta.id, 1),
                meta.name,
                meta.defaultValue > 0.5f
            ));
        } else if (meta.type == ParamType::Integer) {
            layoutParams.push_back(std::make_unique<juce::AudioParameterInt>(
                juce::ParameterID(meta.id, 1),
                meta.name,
                static_cast<int>(meta.min),
                static_cast<int>(meta.max),
                static_cast<int>(meta.defaultValue)
            ));
        } else {
            juce::NormalisableRange<float> range(meta.min, meta.max);
            range.setSkewForCentre(meta.min + (meta.max - meta.min) * meta.skew);
            layoutParams.push_back(std::make_unique<juce::AudioParameterFloat>(
                juce::ParameterID(meta.id, 1),
                meta.name,
                range,
                meta.defaultValue
            ));
        }
    }

    return { layoutParams.begin(), layoutParams.end() };
}

} // namespace ABDMS2000
