import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const buildNum = `${now.getFullYear()}.${pad(now.getMonth() + 1)}.${pad(now.getDate())}.${pad(now.getHours())}${pad(now.getMinutes())}`;
const buildTime = now.toISOString();

console.log(`Updating Build Version: ${buildNum} (${buildTime})...`);

// 1. Generate Source/Core/BuildVersion.h
const buildHeaderPath = path.join(rootDir, 'Source', 'Core', 'BuildVersion.h');
fs.mkdirSync(path.dirname(buildHeaderPath), { recursive: true });

const buildHeaderContent = `// AUTO-GENERATED BY build_webui.js - DO NOT EDIT MANUALLY
#pragma once

namespace ABDMS2000 {
    inline constexpr const char* kVersionString = "1.0.0";
    inline constexpr const char* kBuildNumber = "${buildNum}";
    inline constexpr const char* kBuildTimestamp = "${buildTime}";
    inline constexpr const char* kProductName = "ABDMS2000";
    inline constexpr const char* kManufacturer = "ajabadia";
}
`;

fs.writeFileSync(buildHeaderPath, buildHeaderContent, 'utf8');

// 2. Generate WebUI/src/contracts/buildVersion.js
const buildJsPath = path.join(rootDir, 'WebUI', 'src', 'contracts', 'buildVersion.js');
fs.mkdirSync(path.dirname(buildJsPath), { recursive: true });

const buildJsContent = `// AUTO-GENERATED BY build_webui.js - DO NOT EDIT MANUALLY

export const BUILD_INFO = Object.freeze({
  version: "1.0.0",
  buildNumber: "${buildNum}",
  timestamp: "${buildTime}",
  productName: "ABDMS2000",
  manufacturer: "ajabadia"
});
`;

fs.writeFileSync(buildJsPath, buildJsContent, 'utf8');

console.log('Build version artifacts updated successfully!');
