#!/usr/bin/env node
/**
 * ABDMS2000 — Korg channel byte generator
 *
 * Emite el byte de canal (`3n`) de las tramas de Korg **tal como lo calcula el ABD Bank
 * Manager**, como header C++: así el test del `SysExManager` consume los bytes que emite
 * el contrato en vez de repetir la fórmula.
 *
 * Para qué existe: el C++ y el TS tienen que direccionar el equipo con el **mismo** canal y
 * ninguno de los dos puede llamar al otro en tiempo de ejecución. Repetir la fórmula en el
 * test es justo como se cuela un desplazamiento de uno (que es lo que pasó: el Banco emitía
 * `0x30 | canal` y el plugin `0x30 | (canal - 1)`), así que el test del parser
 * ([Test 25] de `Source/Tests/DSPCoreTests.cpp`) **consume las tramas de este header** y
 * comprueba que la respuesta del plugin sale en el mismo byte que entró.
 *
 * Ojo con qué prueba cada pieza:
 *  - este header + Test 25 → las dos partes **coinciden** (si alguien cambia un lado, el
 *    header regenerado cambia y el test lo ve);
 *  - `ABDBankManager/WebUI/tests/unit/korgChannelConvention.test.js` → la **convención** es
 *    la decidida (`0x30 | (canal - 1)`), con su evidencia y el pin para revertirla.
 *
 * Cadena de procedencia (una sola fuente, artefactos generados):
 *   ABDBankManager/Source/Contracts/Models/korg-ms2000.ts   (korgChannelByte)
 *     -> ABDBankManager `npm run generate`
 *        -> WebUI/src/contracts/gen/modelContracts.gen.js
 *           -> Scripts/sync_bankmanager.js
 *              -> WebUI/abdbank/src/contracts/gen/modelContracts.gen.js
 *                 -> este script
 *                    -> Source/MIDI/KorgChannel.gen.h
 *
 * Uso: node Scripts/generate_korg_channel.js
 *      (paso 1 de build.bat, siempre tras sincronizar)
 *
 * Ver `DOCS/MS2000_SysEx_Spec.md` §1 y el item 4 de `ROADMAP.md`.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

/** Artefacto sincronizado que exporta los contratos canónicos. */
const CONTRACTS_BUNDLE = path.join(
  rootDir, 'WebUI', 'abdbank', 'src', 'contracts', 'gen', 'modelContracts.gen.js'
);
/** Contrato del que sale la cabecera de Korg (MS2000 y microKORG comparten formato). */
const CONTRACT_MODEL_ID = 'korg-ms2000';
const OUTPUT_H = path.join(rootDir, 'Source', 'MIDI', 'KorgChannel.gen.h');
const CHANNELS = 16;

if (!fs.existsSync(CONTRACTS_BUNDLE)) {
  console.error(`ERROR: no se encontro ${path.relative(rootDir, CONTRACTS_BUNDLE)}`);
  console.error('       Ejecuta antes: node Scripts/sync_bankmanager.js');
  process.exit(1);
}

const bundle = await import(pathToFileURL(CONTRACTS_BUNDLE).href);
const contract = (bundle.allKorgContracts ?? []).find(c => c.modelId === CONTRACT_MODEL_ID);

if (!contract || typeof contract.buildDumpRequest !== 'function') {
  console.error(`ERROR: ${CONTRACT_MODEL_ID}.buildDumpRequest no esta en el bundle de contratos.`);
  console.error('       Revisa ABDBankManager/Source/Contracts/Models/korg-ms2000.ts y resincroniza.');
  process.exit(1);
}

const hex = values => values.map(value => `0x${value.toString(16).toUpperCase().padStart(2, '0')}`);

const channelBytes = [];
const programRequests = [];
const allDataRequests = [];

for (let channel = 1; channel <= CHANNELS; channel++) {
  // Las dos peticiones que manda el Banco, tal cual salen del contrato.
  const program = Array.from(contract.buildDumpRequest(0, channel));
  const allData = Array.from(contract.buildDumpRequest('all', channel));

  for (const [name, frame] of [['program dump request', program], ['all data dump request', allData]]) {
    if (frame.length !== 6 || frame[0] !== 0xF0 || frame[1] !== 0x42
        || frame[3] !== 0x58 || frame[frame.length - 1] !== 0xF7) {
      console.error(`ERROR: ${name} del canal ${channel} no es una peticion Korg valida: ${hex(frame).join(' ')}`);
      process.exit(1);
    }
  }
  if (program[2] !== allData[2]) {
    console.error(`ERROR: el canal ${channel} sale con dos bytes distintos (${hex([program[2]])} vs ${hex([allData[2]])})`);
    process.exit(1);
  }

  channelBytes.push(program[2]);
  programRequests.push(program);
  allDataRequests.push(allData);
}

const header = `// AUTO-GENERATED BY Scripts/generate_korg_channel.js - DO NOT EDIT MANUALLY
//
// El byte de canal (\`3n\`) de las tramas de Korg **tal como lo calcula el ABD Bank
// Manager**, derivado del contrato canonico
// (ABDBankManager/Source/Contracts/Models/korg-ms2000.ts -> korgChannelByte) a traves del
// artefacto sincronizado WebUI/abdbank/src/contracts/gen/modelContracts.gen.js.
//
// Para que existe: el C++ y el TS tienen que direccionar el equipo con el MISMO canal y
// ninguno puede llamar al otro en tiempo de ejecucion. Repetir la formula en el test es como
// se cuela un desplazamiento de uno (paso: el Banco emitia 0x30 | canal y el plugin
// 0x30 | (canal - 1)), asi que Test 25 consume las tramas de aqui y comprueba que la
// respuesta del plugin sale en el mismo byte que entro.
//
// Regenerar tras cualquier cambio de contrato:
//   node Scripts/generate_korg_channel.js
// (lo hace el paso 1 de build.bat, tras sincronizar)
//
// Ver DOCS/MS2000_SysEx_Spec.md §1 y el item 4 de ROADMAP.md.

#pragma once

#include <cstdint>

namespace ABDMS2000
{

/** Canales MIDI direccionables (1..16); \`kKorg*[0]\` es el canal 1. */
inline constexpr int kKorgChannelCount = ${CHANNELS};

/**
 * Byte \`3n\` por canal MIDI, tal como lo emite el contrato del Bank Manager.
 * Canal 1 -> ${hex([channelBytes[0]])[0]}, canal 16 -> ${hex([channelBytes[CHANNELS - 1]])[0]}.
 */
inline constexpr uint8_t kKorgChannelByte[kKorgChannelCount] = {
${channelBytes.map(value => `    ${hex([value])[0]},`).join('\n')}
};

/** \`F0 42 3n 58 10 F7\` por canal: la peticion de programa del Banco (comando 0x10). */
inline constexpr uint8_t kKorgProgramDumpRequest[kKorgChannelCount][6] = {
${programRequests.map(frame => `    { ${hex(frame).join(', ')} },`).join('\n')}
};

/** \`F0 42 3n 58 0E F7\` por canal: la peticion de memoria completa (comando 0x0E). */
inline constexpr uint8_t kKorgAllDataDumpRequest[kKorgChannelCount][6] = {
${allDataRequests.map(frame => `    { ${hex(frame).join(', ')} },`).join('\n')}
};

} // namespace ABDMS2000
`;

fs.mkdirSync(path.dirname(OUTPUT_H), { recursive: true });
fs.writeFileSync(OUTPUT_H, header, 'utf8');

console.log(
  `OK - ${path.relative(rootDir, OUTPUT_H)} ` +
  `(canal 1 = ${hex([channelBytes[0]])[0]}, canal 16 = ${hex([channelBytes[CHANNELS - 1]])[0]})`
);
