import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { validateAndProcess, formatFloat } from './registry_core.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const specPath = path.join(rootDir, 'schemas', 'parameters-spec.schema.v1.json');

if (!fs.existsSync(specPath)) {
  console.error(`Spec file not found at: ${specPath}`);
  process.exit(1);
}

const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));

// 1. Normalize + validate the spec, auto-compute sysex offsets
const { processed: withOffsets, errors, sysexCount: sysexCounter } = validateAndProcess(spec.parameters);

if (errors.length > 0) {
  console.error('❌ Registry spec validation failed:');
  errors.forEach(e => console.error(`  - ${e}`));
  process.exit(1);
}

const params = withOffsets; // normalized + with sysexOffset attached

console.log(`Generating registry for ${params.length} parameters (${sysexCounter} with SysEx offsets)...`);

// Emit spec to .gen.js with the computed offsets injected, so WebUI consumers

// keep the same shape (null = no SysEx offset) without hand-maintaining values.
const emitSpec = {
  ...spec,
  parameters: withOffsets.map(p => {
    const { sysex, sysexOffset, ...rest } = p;
    return { ...rest, sysexOffset: sysexOffset < 0 ? null : sysexOffset };
  }),
};

// 2. Generate ParameterRegistry.gen.h
const genHeaderPath = path.join(rootDir, 'Source', 'State', 'ParameterRegistry.gen.h');
fs.mkdirSync(path.dirname(genHeaderPath), { recursive: true });

let hContent = `// AUTO-GENERATED BY registry_generator.js - DO NOT EDIT MANUALLY
#pragma once
#if __has_include(<juce_audio_processors/juce_audio_processors.h>)
#include <juce_audio_processors/juce_audio_processors.h>
#define ABD_HAS_JUCE 1
#else
#define ABD_HAS_JUCE 0
#endif
#include <string>
#include <vector>
#include <unordered_map>

namespace ABDMS2000 {

enum class ParamType {
    Continuous,
    Integer,
    Choice,
    Boolean
};

struct ParameterMeta {
    const char* id;
    const char* name;
    const char* group;
    int cc; // -1 if none
    float min;
    float max;
    float defaultValue;
    float skew;
    ParamType type;
    const char* unit;
    int sysexOffset; // -1 if none (auto-computed by generator)
    std::vector<const char*> choices;
};

class ParameterRegistry {
public:
    static const std::vector<ParameterMeta>& getAllParameters();
    static const ParameterMeta* getParameter(const std::string& id);
#if ABD_HAS_JUCE
    static juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();
#endif
};

namespace ParamIDs {
`;

params.forEach(p => {
  hContent += `    inline constexpr const char* ${p.id} = "${p.id}";\n`;
});

hContent += `} // namespace ParamIDs
} // namespace ABDMS2000
`;

fs.writeFileSync(genHeaderPath, hContent, 'utf8');

// 3. Generate ParameterRegistry.gen.cpp
const genCppPath = path.join(rootDir, 'Source', 'State', 'ParameterRegistry.gen.cpp');
let cppContent = `// AUTO-GENERATED BY registry_generator.js - DO NOT EDIT MANUALLY
#include "ParameterRegistry.gen.h"

namespace ABDMS2000 {

static const std::vector<ParameterMeta> kAllParameters = {
`;

withOffsets.forEach((p, idx) => {
  const ccVal = (p.cc !== null && p.cc !== undefined) ? p.cc : -1;
  const sysexVal = p.sysexOffset;
  const minVal = formatFloat(p.min);
  const maxVal = formatFloat(p.max);
  const defVal = formatFloat(p.default);
  const skewVal = formatFloat(p.skew || 1.0);
  const unitVal = p.unit ? `"${p.unit}"` : '""';

  let typeEnum = 'ParamType::Continuous';
  if (p.type === 'integer') typeEnum = 'ParamType::Integer';
  else if (p.type === 'choice') typeEnum = 'ParamType::Choice';
  else if (p.type === 'boolean') typeEnum = 'ParamType::Boolean';

  let choicesInit = '{}';
  if (p.choices && p.choices.length > 0) {
    choicesInit = `{ ${p.choices.map(c => `"${c}"`).join(', ')} }`;
  }

  cppContent += `    { "${p.id}", "${p.name}", "${p.group}", ${ccVal}, ${minVal}, ${maxVal}, ${defVal}, ${skewVal}, ${typeEnum}, ${unitVal}, ${sysexVal}, ${choicesInit} }`;
  if (idx < params.length - 1) cppContent += ',';
  cppContent += '\n';
});

cppContent += `};

const std::vector<ParameterMeta>& ParameterRegistry::getAllParameters() {
    return kAllParameters;
}

const ParameterMeta* ParameterRegistry::getParameter(const std::string& id) {
    static const std::unordered_map<std::string, const ParameterMeta*> kLookup = []() {
        std::unordered_map<std::string, const ParameterMeta*> map;
        for (const auto& meta : kAllParameters) {
            map[meta.id] = &meta;
        }
        return map;
    }();

    auto it = kLookup.find(id);
    return (it != kLookup.end()) ? it->second : nullptr;
}

#if ABD_HAS_JUCE
juce::AudioProcessorValueTreeState::ParameterLayout ParameterRegistry::createParameterLayout() {
    std::vector<std::unique_ptr<juce::RangedAudioParameter>> layoutParams;

    for (const auto& meta : kAllParameters) {
        if (meta.type == ParamType::Choice && !meta.choices.empty()) {
            juce::StringArray choiceArray;
            for (const auto* c : meta.choices) {
                choiceArray.add(c);
            }
            layoutParams.push_back(std::make_unique<juce::AudioParameterChoice>(
                juce::ParameterID(meta.id, 1),
                meta.name,
                choiceArray,
                static_cast<int>(meta.defaultValue)
            ));
        } else if (meta.type == ParamType::Boolean) {
            layoutParams.push_back(std::make_unique<juce::AudioParameterBool>(
                juce::ParameterID(meta.id, 1),
                meta.name,
                meta.defaultValue > 0.5f
            ));
        } else if (meta.type == ParamType::Integer) {
            layoutParams.push_back(std::make_unique<juce::AudioParameterInt>(
                juce::ParameterID(meta.id, 1),
                meta.name,
                static_cast<int>(meta.min),
                static_cast<int>(meta.max),
                static_cast<int>(meta.defaultValue)
            ));
        } else {
            juce::NormalisableRange<float> range(meta.min, meta.max);
            if (meta.skew > 0.01f && meta.skew < 0.99f) {
                range.setSkewForCentre(meta.min + (meta.max - meta.min) * meta.skew);
            }
            layoutParams.push_back(std::make_unique<juce::AudioParameterFloat>(
                juce::ParameterID(meta.id, 1),
                meta.name,
                range,
                meta.defaultValue
            ));
        }
    }

    return { layoutParams.begin(), layoutParams.end() };
}
#endif

} // namespace ABDMS2000
`;

fs.writeFileSync(genCppPath, cppContent, 'utf8');

// 4. Generate registry.gen.js
const genJsPath = path.join(rootDir, 'WebUI', 'src', 'contracts', 'registry.gen.js');
fs.mkdirSync(path.dirname(genJsPath), { recursive: true });

let jsContent = `// AUTO-GENERATED BY registry_generator.js - DO NOT EDIT MANUALLY

export const PARAMETERS_SPEC = ${JSON.stringify(emitSpec, null, 2)};

export const PARAM_LOOKUP = Object.freeze(
  PARAMETERS_SPEC.parameters.reduce((acc, param) => {
    acc[param.id] = param;
    return acc;
  }, {})
);

export const PARAM_IDS = Object.freeze(
  PARAMETERS_SPEC.parameters.reduce((acc, param) => {
    acc[param.id] = param.id;
    return acc;
  }, {})
);

export const PARAM_LIST = Object.freeze(PARAMETERS_SPEC.parameters);
`;

fs.writeFileSync(genJsPath, jsContent, 'utf8');

console.log('✅ Registry artifacts successfully generated!');
console.log(`   SysEx offset map: ${withOffsets.filter(p => p.sysexOffset >= 0).length} params, max=${sysexCounter - 1}`);
