// AUTO-GENERATED BY build_webui.js - DO NOT EDIT MANUALLY

export const BUILD_INFO = Object.freeze({
  version: "1.0.0",
  buildNumber: "2026.08.24.1511",
  timestamp: "2026-08-24T13:11:45.677Z",
  productName: "ABDMS2000",
  manufacturer: "ajabadia"
});
