// AUTO-GENERATED BY build_webui.js - DO NOT EDIT MANUALLY

export const BUILD_INFO = Object.freeze({
  version: "1.0.0",
  buildNumber: "2026.08.24.1824",
  timestamp: "2026-08-24T16:24:51.586Z",
  productName: "ABDMS2000",
  manufacturer: "ajabadia"
});
